version: '3.8'
services:
  backend:
    build: ./
    ports:
      - "3037:80"
    restart: always
    volumes:
      - /filestorages:/filestorages      
    networks:
      - rede_nova
networks:
  rede_nova:
    name: rede_nova
    external: true